// Generated by scripts/generate-native-contract.ts from the canonical Rust DTOs. Do not edit.
import * as z from "zod";

export const CONTRACT_VERSION = 1 as const;
export const REVISION_NOTICE_EVENT = "sanitized-desktop-state-revision" as const;

export const codingProviderSchema = z.enum(["codex","claude"]);
export const quotaLaneSchema = z.object({ allowance: z.number().nullable().optional(), label: z.string().min(1), remaining: z.number().nullable().optional(), resetAt: z.string().datetime().nullable().optional(), unit: z.string().min(1) }).strict();
export const providerSnapshotSchema = z.discriminatedUnion("availability", [z.object({ availability: z.literal("unavailable"), provider: codingProviderSchema, quotaLanes: z.tuple([]) }).strict(), z.object({ availability: z.literal("current"), observedAt: z.string().datetime(), provider: codingProviderSchema, quotaLanes: z.array(quotaLaneSchema).min(1) }).strict(), z.object({ availability: z.literal("stale"), observedAt: z.string().datetime(), provider: codingProviderSchema, quotaLanes: z.array(quotaLaneSchema).min(1) }).strict()]);
export const syncStatusSchema = z.enum(["synced","pending","stale","unavailable"]);
export const syncStateSchema = z.object({ lastSuccessfulAt: z.string().datetime().nullable().optional(), status: syncStatusSchema }).strict();
export const usageCoverageSchema = z.enum(["complete","partial"]);
export const usageEvidenceBasisSchema = z.enum(["provider-reported","locally-derived"]);
export const usageTotalSchema = z.discriminatedUnion("availability", [z.object({ availability: z.literal("unavailable") }).strict(), z.object({ apiEquivalentCostUsd: z.number().nonnegative().nullable().optional(), availability: z.literal("current"), coverage: usageCoverageSchema, evidenceBasis: usageEvidenceBasisSchema, observedAt: z.string().datetime(), observedTokens: z.number().int().nonnegative() }).strict(), z.object({ apiEquivalentCostUsd: z.number().nonnegative().nullable().optional(), availability: z.literal("stale"), coverage: usageCoverageSchema, evidenceBasis: usageEvidenceBasisSchema, observedAt: z.string().datetime(), observedTokens: z.number().int().nonnegative() }).strict()]);
export const usagePeriodsSchema = z.object({ sevenDays: usageTotalSchema, thirtyDays: usageTotalSchema, today: usageTotalSchema }).strict();
export const usageByProviderSchema = z.object({ claude: usagePeriodsSchema, codex: usagePeriodsSchema }).strict();
export const sanitizedDesktopStateSchema = z.object({ contractVersion: z.literal(1), generatedAt: z.string().datetime(), providers: z.tuple([providerSnapshotSchema, providerSnapshotSchema]), revision: z.string().regex(/^[1-9]\d*$/), sync: syncStateSchema, usage: usageByProviderSchema }).strict();
export const refreshReceiptSchema = z.object({ accepted: z.boolean() }).strict();
export const revisionNoticeSchema = z.object({ revision: z.string().regex(/^[1-9]\d*$/) }).strict();

export type CodingProvider = z.infer<typeof codingProviderSchema>;
export type QuotaLane = z.infer<typeof quotaLaneSchema>;
export type ProviderSnapshot = z.infer<typeof providerSnapshotSchema>;
export type SyncStatus = z.infer<typeof syncStatusSchema>;
export type SyncState = z.infer<typeof syncStateSchema>;
export type UsageCoverage = z.infer<typeof usageCoverageSchema>;
export type UsageEvidenceBasis = z.infer<typeof usageEvidenceBasisSchema>;
export type UsageTotal = z.infer<typeof usageTotalSchema>;
export type UsagePeriods = z.infer<typeof usagePeriodsSchema>;
export type UsageByProvider = z.infer<typeof usageByProviderSchema>;
export type SanitizedDesktopState = z.infer<typeof sanitizedDesktopStateSchema>;
export type RefreshReceipt = z.infer<typeof refreshReceiptSchema>;
export type RevisionNotice = z.infer<typeof revisionNoticeSchema>;
